const familila = [
	{
		nombre: 'Jazmin',
		edad: 34,
		nac: 'CDMX',
		genero: 'Femenino',
		parentesco: 'Padre',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Fher',
		edad: 35,
		nac: 'CDMX',
		genero: 'Masculino',
		parentesco: 'Padre',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Dafne',
		edad: 20,
		nac: 'CDMX',
		genero: 'Femenino',
		parentesco: 'Hijo',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Derek',
		edad: 4,
		nac: 'Celaya',
		genero: 'Masculio',
		parentesco: 'Hijo',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Natalie',
		edad: 2,
		nac: 'Celaya',
		genero: 'Femenino',
		parentesco: 'Hijo',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Lety',
		edad: 63,
		nac: 'CDMX',
		genero: 'Femenino',
		parentesco: 'Abuelo',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Fer Rangel',
		edad: 70,
		nac: 'CDMX',
		genero: 'Masculio',
		parentesco: 'Abuelo',
		ubicacion: 'Gto',
		vivo: false,
	},
	{
		nombre: 'Tere',
		edad: 53,
		nac: 'CDMX',
		genero: 'Femenino',
		parentesco: 'Abuelo',
		ubicacion: 'Mor',
		vivo: true,
	},
	{
		nombre: 'Tibur',
		edad: 56,
		nac: 'CDMX',
		genero: 'Masculio',
		parentesco: 'Abuelo',
		ubicacion: 'Mor',
		vivo: true,
	},
	{
		nombre: 'Ale',
		edad: 35,
		nac: 'Celaya',
		genero: 'Femenino',
		parentesco: 'Tio',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Robert',
		edad: 37,
		nac: 'Celaya',
		genero: 'Masculino',
		parentesco: 'Tio',
		ubicacion: 'Gto',
		vivo: true,
	},
	{
		nombre: 'Erik',
		edad: 397,
		nac: 'CDMX',
		genero: 'Masculino',
		parentesco: 'Tio',
		ubicacion: 'Pens',
		vivo: true,
	},
	{
		nombre: 'Anahi',
		edad: 41,
		nac: 'Puebla',
		genero: 'Femenino',
		parentesco: 'Tio',
		ubicacion: 'Pens',
		vivo: true,
	},
	{
		nombre: 'Healy',
		edad: 15,
		nac: 'Pensilvania',
		genero: 'Femenino',
		parentesco: 'Primo',
		ubicacion: 'Pens',
		vivo: true,
	},
	{
		nombre: 'Bealy',
		edad: 4,
		nac: 'Pensilvania',
		genero: 'Femenino',
		parentesco: 'Primo',
		ubicacion: 'Pens',
		vivo: true,
	},
	{
		nombre: 'Jerick',
		edad: 1,
		nac: 'Pensilvania',
		genero: 'Masculino',
		parentesco: 'Primo',
		ubicacion: 'Pens',
		vivo: true,
	},
];
